language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
    - phpunit --configuration phpunit.xml.dist

matrix:
  fast_finish: true
